name: Assignment Workflow

run-name: Assignment 2

on: [push]

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v3
      - name: Step 2 - Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Step 3 - Cache node modules
        id: cache-npm-mod
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
      - if: steps.cache-npm-mod.outputs.cache-hit != 'true'
        name: List the node modules state
        continue-on-error: true
        run: npm list
      - name: Step 3 - Install Node
        # if: steps.cache-npm-mod.outputs.cache-hit != 'true'
        run: npm i
      - name: Cache check
        run: echo ${{ steps.cache-dependencies.outputs.cache-hit == 'true' && "It was a cache hit" || "Its was a cache miss" }}
      - name: Step 4 - Run test
        run: npm run test

  buildjob:
    runs-on: ubuntu-latest
    needs: testjob
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v3
      - name: Step 2 - Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Step 3 - Cache node modules
        id: cache-npm-mod
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Step 4 - Install
        # if: steps.cache-npm-mod.outputs.cache-hit != 'true'
        run: npm i
      - name: Step 4 - Run build
        run: npm run build
