name: On Every branch runner

on: [push]

jobs:
  script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: echo " This Job runs on every branch for just displaying runablity of the workflow"
